Validations
Shot-Callers/shotcaller-app-backend pull request #3
Opened 2024-01-05 23:54 UTC by lilGuzi

2024-01-06 00:00 UTC, elysemontano requested changes
I am seeing a lot of work that goes beyond what the Trello card is calling for.  For instance, I am seeing some JWT configs and your controller methods.  This PR should be ONLY validations and model specs

2024-01-06 00:00 UTC, elysemontano commented on README.md
> +3750c7a03a8b0a175a00ab24263df356de54043ebf51d9cebcf05db974b9ec0c5a13546abc3cac9856f59b521ec73c4b2ae003d9414040f1c98c859eec73ab15
Is this needed?

2024-01-06 00:17 UTC, lilGuzi commented on README.md
> +3750c7a03a8b0a175a00ab24263df356de54043ebf51d9cebcf05db974b9ec0c5a13546abc3cac9856f59b521ec73c4b2ae003d9414040f1c98c859eec73ab15
updated Trello cards to include controller methods. also removed the seceret key from the README.

2024-01-08 17:44 UTC, elysemontano approved these changes

2024-01-08 17:44 UTC, elysemontano commented on spec/models/basketball_court_spec.rb
> +    attributes.each do |attr|
Cool approach!

2024-01-08 17:48 UTC, merged